# Generated by Django 2.1.5 on 2020-12-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('HOUSE', 'House'), ('FLAT', 'Flat')], default='HOUSE', max_length=100, verbose_name='Type')),
                ('price', models.FloatField()),
                ('size', models.FloatField(verbose_name='Size(m2)')),
                ('city', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
            ],
        ),
    ]
