# Generated by Django 2.1.5 on 2020-12-09 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('post_text', models.TextField(verbose_name='Text')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Posted Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('USED', 'Used'), ('NEW', 'New')], default='NEW', max_length=50)),
                ('delivery', models.CharField(choices=[('SHIPMENT', 'Shipment'), ('PICK UP', 'Pick up')], max_length=50)),
                ('price', models.FloatField()),
                ('list_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('major', models.CharField(max_length=200)),
            ],
        ),
    ]
