# Generated by Django 2.1.5 on 2020-10-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option1_votes', models.IntegerField(default=0)),
                ('option2_votes', models.IntegerField(default=0)),
                ('option3_votes', models.IntegerField(default=0)),
            ],
        ),
    ]
